### ISSUE TITLE
AssertionError due to saving configuration

### ISSUE THREAD

**Issue by a005** [foxel/python_ndms2_client#3]
When trying to save the router configuration from the web interface the AssertionError rised in ndms2_client/client.py:
```
File "/usr/local/lib/python3.7/site-packages/ndms2_client/client.py", line 53, in get_associated_devices
    associations = _parse_dict_lines(self._connection.run_command(_ASSOCIATIONS_CMD))
File "/usr/local/lib/python3.7/site-packages/ndms2_client/client.py", line 128, in _parse_dict_lines
    assert len(fixed_lines) > 0, "Found a line with no colon in the beginning of the file"
```
Via the telnet its looks like an unwanted (and unparsed) event from ndms:
```
(config)> show associations
(config)>

System event, class = "Event::Type::ConfigurationSaved"

(config)>
```
This assert brokes the normal flow of the device_tracker in HomeAssistant
`assert len(fixed_lines) > 0, "Found a line with no colon in the beginning of the file"`

**Comment by foxel** [comment]
Thanks @a005 
I've fixed this and created a PR for HA
